projects:
  - name: "WORKOUT TRACKER 🏋🏻"
    period: "July 2022"
    description: |
      WorkoutTracker is a Fitness App that uses Augmented Reality and Computer Vision to track repetitions of exercises for you. It also memorizes the order of exercises and provides reminders for the next exercise.
    technologies:
      - iOS
      - Swift
      - SwiftUI
    github: "https://github.com/Davydhh/WorkoutTracker"
    live_demo: "https://youtube.com/shorts/pQXOGQ_unDc?si=jk1EsxEdMWbwd8kX"
    image_path: "/workout.jpg"

  - name: "COVID-19 TRACKER 🦠"
    period: "February 2020"
    description: |
      My COVID-19 Tracker Android app provides real-time information about the spread of COVID-19 in Italy. The app offers data at the national, regional, and city levels, allowing users to stay informed about the latest statistics and trends.
    technologies:
      - Android
      - Java
    github: "https://github.com/Davydhh/Covid-19"
    live_demo: "https://youtu.be/pNddCViY9oI?si=uyznrarIsA_7Zcmj"
    image_path: "/covid.jpg"

content_page:
  card_titles:
    - Software Engineer
    - Microservices Developer
    - Java Developer
  short_description: "A dedicated Backend Developer based in Milan, Italy 📍"
  medium_description: "I'm a Software Engineer experienced in Java, Python, Microservices, and Cloud Computing. Skilled in building secure and scalable applications. Adaptable team player with strong communication, working well in Agile and Waterfall environments."
  about_me: "ABOUT ME"
  tech_stack: "Tech Stack"
  hello: "Hi - I'm Davide"
  projects: "PROJECTS"
  projects_introduction: "An iOS app and an Android app 📱"

contacts:
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/davide-cazzetta-3a86a9198"
    image_path: "/linkedin.jpg"
  - name: "GitHub"
    link: "https://github.com/Davydhh"
    image_path: "/github.jpg"

footer:
  copyright: "Copyright © 2023. All rights reserved"

header:
  buttons:
    - title: "Home"
      href: "/"
    - title: "About"
      href: "/about"
    - title: "Projects"
      href: "/projects"
    - title: "Contact"
      href: "/contact"
  title: "Davide.dev"

about_page:
  my_story: |
    Hello, my name is Davide and I was born in Italy in 1998. Since I was a child I have always been passionate about technology, a passion so strong that it drove me to complete a 5-year university degree and then turn my passion into a job. 
    I love learning new things to improve my skills. 

    For me, Informatics means creativity and limitlessness, you can create anything, the only limit is our mind.
  experience:
    - title: "Software Engineer"
      company: "Robert Bosch S.p.a."
      description: |
        I am a dedicated Backend Developer with experience in Java, Python, Microservices, and Cloud Computing.
  education:
    - title: "Bachelor degree"
      institution: ""
      grade: 100
